name = "photogram-wasm-demo"
compatibility_date = "2024-07-18"
pages_build_output_dir = "dist"

[build]
command = "npm run build"
cwd = "/"

[build.environment]
NODE_VERSION = "18"
RUST_VERSION = "1.70.0"

# Headers for WASM files to ensure proper loading
[[headers]]
for = "*.wasm"
[headers.values]
"Content-Type" = "application/wasm"
"Cross-Origin-Embedder-Policy" = "require-corp"
"Cross-Origin-Opener-Policy" = "same-origin"

# Additional headers for JS files from WASM
[[headers]]
for = "*.js"
[headers.values]
"Cross-Origin-Embedder-Policy" = "require-corp"
"Cross-Origin-Opener-Policy" = "same-origin"
